### ISSUE TITLE
Write tests for Field.build_rabi_freq_t_func method

### ISSUE THREAD

**Issue by tpogden** [tpogden/maxwellbloch#16]
# Motivation

Test coverage for this method.

# Tasks

The following cases should be covered:
- [ ] The t_func argument is `None` (i.e. no time dependence)
- [ ] The t_func argument is a correct string (e.g. `'square_1'`, `'ramp_onoff_2'`)
- [ ] The t_func argument is an incorrect string (e.g. `'foo_1'`)
